export const TestIDs = {
  HEADER: 'HEADER',
  HEADER_GREETINGS: 'HEADER_GREETINGS',
  HEADER_TITLE: 'HEADER_TITLE',

  HEALTH_STEP_SECTION: 'HEALTH_STEP_SECTION',
  HEALTH_STEP_NAME: 'HEALTH_STEP_NAME',
  HEALTH_STEP_VALUE: 'HEALTH_STEP_VALUE',
  HEALTH_STEP_DESCRIPTION: 'HEALTH_STEP_DESCRIPTION',

  REQUEST_PERMISSION_SECTION: 'REQUEST_PERMISSION_SECTION',
  REQUEST_PERMISSION_BUTTON: 'REQUEST_PERMISSION_BUTTON',
};
